"""Generate the fake lab's docker compose file from a topology.

    python -m netops_fakes.compose ../lab/fakelab/topology.yaml

``make fakelab-compose`` writes the output to deploy/docker-compose.fakelab.yml. One
container per served device and management address, with that address on the ``fakelab``
network; the worker joins that network so discovery can reach them. A test keeps the
committed file in sync with the topology.
"""

import argparse
import ipaddress
from pathlib import Path

import yaml

from netops_fakes.topology import Topology, load

HEADER = """\
# GENERATED by `make fakelab-compose` (python -m netops_fakes.compose) from
# lab/fakelab/topology.yaml. Do not edit by hand.
#
# The fake lab: one container per fake device (and per extra management address) on the
# fakelab network, used together with docker-compose.yml:
#   make fakelab-up        start the stack and the fake devices
#   make fakelab-seed      create the fake lab's credential profiles
#   make fakelab-discover  discover the fake lab from core1
#   make fakelab-down      stop everything
# The worker joins the fakelab network, so discovery reaches the devices at their
# management addresses. Nothing here is reachable from outside the host.
"""


def network_of(topology: Topology) -> ipaddress.IPv4Network:
    """The /24 the containers live in: the fake lab's management addresses."""
    return ipaddress.IPv4Network(f"{topology.devices[0].mgmt_ip}/24", strict=False)


def render(topology: Topology, topology_path: str = "../lab/fakelab/topology.yaml") -> str:
    network = network_of(topology)
    hosts = list(network.hosts())
    gateway, ip_range = hosts[-1], ipaddress.IPv4Network(f"{hosts[-32]}/28", strict=False)
    services: dict[str, object] = {}
    for device in topology.devices:
        if device.external:
            continue
        addresses = [device.mgmt_ip, *(svi.ip for svi in device.extra_svis)]
        for index, address in enumerate(addresses):
            if address not in network:
                raise ValueError(f"{device.name}: {address} is outside {network}")
            name = f"fake-{device.name}" + (f"-{index + 1}" if index else "")
            services[name] = {
                "<<": "*fake-device",
                "command": ["/lab/topology.yaml", device.name],
                "networks": {"fakelab": {"ipv4_address": str(address)}},
            }
    services["worker"] = {"networks": {"default": {}, "fakelab": {}}}
    document = {
        "services": services,
        "networks": {
            "fakelab": {
                "ipam": {
                    "config": [
                        {
                            "subnet": str(network),
                            # Addresses Docker may give the worker; no device uses them.
                            "ip_range": str(ip_range),
                            "gateway": str(gateway),
                        }
                    ]
                }
            }
        },
    }
    anchor = f"""\
x-fake-device: &fake-device
  build:
    context: ../backend
    target: fakelab
  image: netops-fakelab:dev
  restart: unless-stopped
  profiles: [fakelab]
  environment:
    FAKELAB_USERNAME: ${{FAKELAB_USERNAME:-netops-ro}}
    FAKELAB_PASSWORD: ${{FAKELAB_PASSWORD:?run make fakelab-up, which adds it to deploy/.env}}
  volumes:
    - {topology_path}:/lab/topology.yaml:ro
  # Port 22 without root inside the container.
  sysctls:
    net.ipv4.ip_unprivileged_port_start: "0"

"""
    body = yaml.safe_dump(document, sort_keys=False, default_flow_style=False, width=100)
    body = body.replace("'<<': '*fake-device'", "<<: *fake-device")
    return HEADER + "\n" + anchor + body


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Generate the fake lab's compose file.")
    parser.add_argument("topology", type=Path)
    args = parser.parse_args(argv)
    print(render(load(args.topology)), end="")  # noqa: T201 - the output is the product


if __name__ == "__main__":
    main()
